server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://52.78.66.0:9000
#          issuer-uri: http://127.0.0.1:9000
          issuer-uri: http://auth-server:9000
